name = "e-umm-frontend"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

# Cloudflare Pages 설정
[env.production]
name = "e-umm-frontend"

# 환경 변수 (빌드 시 사용)
[env.production.vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://eume-api.hwjinfo.workers.dev"

# Pages configuration - no build section needed for manual deploy

# Preview 환경 설정
[env.preview]
name = "e-umm-frontend-preview"

[env.preview.vars]
NODE_ENV = "development"
VITE_API_BASE_URL = "https://eume-api.hwjinfo.workers.dev"